[workspace]

members = [
    "intcode",
    "day-01-the-tyranny-of-the-rocket-equation",
    "day-02-1202-program-alarm",
    "day-05-sunny-with-a-chance-of-asteroids",
    "day-07-amplification-circuit",
    "day-09-sensor-boost"
]

[profile.test]
opt-level = 3