[package]
name = "aoc-2022-15"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aoc_2022_utils = { path = "../../utils" }

[dev-dependencies]
rstest.workspace = true
criterion.workspace = true

[[bench]]
name = "solution"
harness = false
