[package]
name = "aoc-2022-10"
version.workspace = true
edition.workspace = true
license.workspace = true

[dev-dependencies]
rstest.workspace = true
criterion.workspace = true

[[bench]]
name = "solution"
harness = false
