[package]
name = "aoc-2023-11"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aoc_2023_utils = { path = "../../utils" }

[dev-dependencies]
rstest.workspace = true
criterion.workspace = true

[[bench]]
name = "solution"
harness = false
